### ISSUE TITLE
Multi-core parallelization/GPU support

### ISSUE THREAD

**Issue by deHasara** [leiyangleon/autoRIFT#12]
Hi,
I'm Hasara, currently working as a RA at the University of Moratuwa, Sri Lanka. I'm currently working on slow-moving landslide detection using the SAR time series analysis. I thought of applying autoRIFT algorithm for this purpose. Since the dataset is very large, I think parallelization would be a mandatory requirement for my task. I saw that this multi-core support was mentioned as a possible enhancement in the repo. However, I would like to work on implementing this feature. Any insight would be highly appreciated.

**Comment by leiyangleon** [comment]
Hi, multithreading has been implemented in the core processing of autoRIFT, namely the normalized cross-correlation (NCC). Feel free to download the latest version of the software. This version as well as previous single-core versions are usually pretty efficient for large images such as Sentinel-1 images with dimension of 70000 x 10000. 

If further enhancement is desired, you are welcome to do it in the few lines of [preprocessing](https://github.com/leiyangleon/autoRIFT/blob/c051a63c6f75896033bed3ff6dd617e646aeeabe/geo_autoRIFT/autoRIFT/autoRIFT.py#L109) and [data type conversion](https://github.com/leiyangleon/autoRIFT/blob/c051a63c6f75896033bed3ff6dd617e646aeeabe/geo_autoRIFT/autoRIFT/autoRIFT.py#L209) that are called [here](https://github.com/leiyangleon/autoRIFT/blob/c051a63c6f75896033bed3ff6dd617e646aeeabe/testautoRIFT_ISCE.py#L286-L295) or anything under the mpflag "[MultiThread](https://github.com/leiyangleon/autoRIFT/blob/c051a63c6f75896033bed3ff6dd617e646aeeabe/geo_autoRIFT/autoRIFT/autoRIFT.py#L987)".
